### ISSUE TITLE
Yum in unable to install mysql

### ISSUE THREAD

**Issue by jieliau** [aws-samples/eb-demo-php-simple-app#7]
In _.ebextensions/database.conf_, Yum does not have mysql available for installation. Please replace mysql to mariadb. It's working from my end to deploy EB service on AWS.
```
   packages: 
     yum:
       mariadb: []
```

Thanks.

**Comment by ghost** [comment]
Have to change the table creation command also? I get this error after using mariadb
 Unhandled exception during build: Command create-table failed

**Comment by chknabeel** [comment]
> 

database.config should be updated to this to make it work:

```
packages: 
  yum:
    mariadb-devel: []
container_commands:
  01-create-tables:
    command: "sh db/deployschema.sh"
    ignoreErrors: true
```

db/deployschema.sh should be in root directory of your app.
